name: on specific branch
on: 
  push:
    branches:
      - main
jobs:
  push-main:
    runs-on: ubuntu-latest
    steps:
      - name: run on push
        run: echo "push happend to this main branch"
