name: jobs & steps
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build started
        run: echo "build started"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: check the code
        run: ls -a
