name: jobs & steps
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build started
        run: echo "build started"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: build status
        run: echo "build completed"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing the artifacts
        run: echo "testing is completed"
