name: self runner
on: workflow_dispatch
jobs:
  my-runner:
    runs-on: build-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: list files
        run: ls -a
        
